<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PartidasGenericasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            ['clave'=>111,'clave_concepto'=>1100,"descripcion"=>"Dietas", "anio"=>2021],
            ['clave'=>112,'clave_concepto'=>1100,"descripcion"=>"Haberes", "anio"=>2021],
            ['clave'=>113,'clave_concepto'=>1100,"descripcion"=>"Sueldos Base al Personal Permanente", "anio"=>2021],
            ['clave'=>114,'clave_concepto'=>1100,"descripcion"=>"Remuneraciones por Adscripción Laboral en el Extranjero", "anio"=>2021],

            ['clave'=>121,'clave_concepto'=>1200,"descripcion"=>"Honorarios Asimilables a Salarios", "anio"=>2021],
            ['clave'=>122,'clave_concepto'=>1200,"descripcion"=>"Sueldos Base al Personal Eventual", "anio"=>2021],
            ['clave'=>123,'clave_concepto'=>1200,"descripcion"=>"Retribuciones por Servicios de Carácter Social", "anio"=>2021],
            ['clave'=>124,'clave_concepto'=>1200,"descripcion"=>"Retribución a los Representantes de los Trabajadores y de los Patrones en la Junta de Conciliación y Arbitraje", "anio"=>2021],

            ['clave'=>131,'clave_concepto'=>1300,"descripcion"=>"Primas por Años de Servicios Efectivos Prestados", "anio"=>2021],
            ['clave'=>132,'clave_concepto'=>1300,"descripcion"=>"Primas de Vacaciones, Dominical y Gratificación de Fin de Año", "anio"=>2021],
            ['clave'=>133,'clave_concepto'=>1300,"descripcion"=>"Horas Extraordinarias", "anio"=>2021],
            ['clave'=>134,'clave_concepto'=>1300,"descripcion"=>"Compensaciones", "anio"=>2021],
            ['clave'=>135,'clave_concepto'=>1300,"descripcion"=>"Sobrehaberes", "anio"=>2021],
            ['clave'=>136,'clave_concepto'=>1300,"descripcion"=>"Asignaciones de Técnico, de Mando, por Comisión, de Vuelo y de Técnico Especial", "anio"=>2021],
            ['clave'=>137,'clave_concepto'=>1300,"descripcion"=>"Honorarios Especiales", "anio"=>2021],
            ['clave'=>138,'clave_concepto'=>1300,"descripcion"=>"Participaciones por Vigilancia en el Cumplimiento de las Leyes y Custodia de Valores", "anio"=>2021],

            ['clave'=>141,'clave_concepto'=>1400,"descripcion"=>"Aportaciones de Seguridad Social", "anio"=>2021],
            ['clave'=>142,'clave_concepto'=>1400,"descripcion"=>"Aportaciones a Fondos de Vivienda", "anio"=>2021],
            ['clave'=>143,'clave_concepto'=>1400,"descripcion"=>"Aportaciones al Sistema para el Retiro", "anio"=>2021],
            ['clave'=>144,'clave_concepto'=>1400,"descripcion"=>"Aportaciones para Seguros", "anio"=>2021],

            ['clave'=>151,'clave_concepto'=>1500,"descripcion"=>"Cuotas para el Fondo de Ahorro y Fondo de Trabajo", "anio"=>2021],
            ['clave'=>152,'clave_concepto'=>1500,"descripcion"=>"Indemnizaciones", "anio"=>2021],
            ['clave'=>153,'clave_concepto'=>1500,"descripcion"=>"Prestaciones y Haberes de Retiro", "anio"=>2021],
            ['clave'=>154,'clave_concepto'=>1500,"descripcion"=>"Prestaciones Contractuales", "anio"=>2021],
            ['clave'=>155,'clave_concepto'=>1500,"descripcion"=>"Apoyos a la Capacitación de los Servidores Públicos", "anio"=>2021],
            ['clave'=>159,'clave_concepto'=>1500,"descripcion"=>"Otras Prestaciones Sociales y Económicas", "anio"=>2021],
            
            ['clave'=>161,'clave_concepto'=>1600,"descripcion"=>"Previsiones de Carácter Laboral, Económica y de Seguridad Social", "anio"=>2021],

            ['clave'=>171,'clave_concepto'=>1700,"descripcion"=>"Estímulos", "anio"=>2021],
            ['clave'=>172,'clave_concepto'=>1700,"descripcion"=>"Recompensas", "anio"=>2021],

            ['clave'=>211,'clave_concepto'=>2100,"descripcion"=>"Materiales, Útiles y Equipos Menores de Oficina", "anio"=>2021],
            ['clave'=>212,'clave_concepto'=>2100,"descripcion"=>"Materiales y Útiles de Impresión y Reproducción", "anio"=>2021],
            ['clave'=>213,'clave_concepto'=>2100,"descripcion"=>"Material Estadístico y Geográfico", "anio"=>2021],
            ['clave'=>214,'clave_concepto'=>2100,"descripcion"=>"Materiales, Útiles y Equipos Menores de Tecnologías de la Información y Comunicaciones", "anio"=>2021],
            ['clave'=>215,'clave_concepto'=>2100,"descripcion"=>"Material Impreso e Información Digital", "anio"=>2021],
            ['clave'=>216,'clave_concepto'=>2100,"descripcion"=>"Material de Limpieza", "anio"=>2021],
            ['clave'=>217,'clave_concepto'=>2100,"descripcion"=>"Materiales y Útiles de Enseñanza", "anio"=>2021],
            ['clave'=>218,'clave_concepto'=>2100,"descripcion"=>"Materiales para el Registro e Identificación de Bienes y Personas", "anio"=>2021],

            ['clave'=>221,'clave_concepto'=>2200,"descripcion"=>"Productos Alimenticios para Personas", "anio"=>2021],
            ['clave'=>222,'clave_concepto'=>2200,"descripcion"=>"Productos Alimenticios para Animales", "anio"=>2021],
            ['clave'=>223,'clave_concepto'=>2200,"descripcion"=>"Utensilios para el Servicio de Alimentación", "anio"=>2021],

            ['clave'=>231,'clave_concepto'=>2300,"descripcion"=>"Productos Alimenticios, Agropecuarios y Forestales Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>232,'clave_concepto'=>2300,"descripcion"=>"Insumos Textiles Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>233,'clave_concepto'=>2300,"descripcion"=>"Productos de Papel, Cartón e Impresos Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>234,'clave_concepto'=>2300,"descripcion"=>"Combustibles, Lubricantes, Aditivos, Carbón y sus Derivados Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>235,'clave_concepto'=>2300,"descripcion"=>"Productos Químicos, Farmacéuticos y de Laboratorio Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>236,'clave_concepto'=>2300,"descripcion"=>"Productos Metálicos y a Base de Minerales no Metálicos Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>237,'clave_concepto'=>2300,"descripcion"=>"Productos de Cuero, Piel, Plástico y Hule Adquiridos como Materia Prima", "anio"=>2021],
            ['clave'=>238,'clave_concepto'=>2300,"descripcion"=>"Mercancías Adquiridas para su Comercialización", "anio"=>2021],
            ['clave'=>239,'clave_concepto'=>2300,"descripcion"=>"Otros Productos Adquiridos como Materia Prima", "anio"=>2021],
            
            ['clave'=>241,'clave_concepto'=>2400,"descripcion"=>"Productos Minerales no Metálicos", "anio"=>2021],
            ['clave'=>242,'clave_concepto'=>2400,"descripcion"=>"Cemento y Productos de Concreto", "anio"=>2021],
            ['clave'=>243,'clave_concepto'=>2400,"descripcion"=>"Cal, Yeso y Productos de Yeso", "anio"=>2021],
            ['clave'=>244,'clave_concepto'=>2400,"descripcion"=>"Madera y Productos de Madera", "anio"=>2021],
            ['clave'=>245,'clave_concepto'=>2400,"descripcion"=>"Vidrio y Productos de Vidrio", "anio"=>2021],
            ['clave'=>246,'clave_concepto'=>2400,"descripcion"=>"Material Eléctrico y Electrónico", "anio"=>2021],
            ['clave'=>247,'clave_concepto'=>2400,"descripcion"=>"Artículos Metálicos para la Construcción", "anio"=>2021],
            ['clave'=>248,'clave_concepto'=>2400,"descripcion"=>"Materiales Complementarios", "anio"=>2021],
            ['clave'=>249,'clave_concepto'=>2400,"descripcion"=>"Otros Materiales y Artículos de Construcción y Reparación", "anio"=>2021],

            ['clave'=>251,'clave_concepto'=>2500,"descripcion"=>"Productos Químicos Básicos", "anio"=>2021],
            ['clave'=>252,'clave_concepto'=>2500,"descripcion"=>"Fertilizantes, Pesticidas y Otros Agroquímicos", "anio"=>2021],
            ['clave'=>253,'clave_concepto'=>2500,"descripcion"=>"Medicinas y Productos Farmacéuticos", "anio"=>2021],
            ['clave'=>254,'clave_concepto'=>2500,"descripcion"=>"Materiales, Accesorios y Suministros Médicos", "anio"=>2021],
            ['clave'=>255,'clave_concepto'=>2500,"descripcion"=>"Materiales, Accesorios y Suministros de Laboratorio", "anio"=>2021],
            ['clave'=>256,'clave_concepto'=>2500,"descripcion"=>"Fibras Sintéticas, Hules, Plásticos y Derivados", "anio"=>2021],
            ['clave'=>259,'clave_concepto'=>2500,"descripcion"=>"Otros Productos Químicos", "anio"=>2021],

            ['clave'=>261,'clave_concepto'=>2600,"descripcion"=>"Combustibles, Lubricantes y Aditivos", "anio"=>2021],
            ['clave'=>262,'clave_concepto'=>2600,"descripcion"=>"Carbón y sus Derivados", "anio"=>2021],

            ['clave'=>271,'clave_concepto'=>2700,"descripcion"=>"Vestuario y Uniformes", "anio"=>2021],
            ['clave'=>272,'clave_concepto'=>2700,"descripcion"=>"Prendas de Seguridad y Protección Personal", "anio"=>2021],
            ['clave'=>273,'clave_concepto'=>2700,"descripcion"=>"Artículos Deportivos", "anio"=>2021],
            ['clave'=>274,'clave_concepto'=>2700,"descripcion"=>"Productos Textiles", "anio"=>2021],
            ['clave'=>275,'clave_concepto'=>2700,"descripcion"=>"Blancos y Otros Productos Textiles, Excepto Prendas de Vestir", "anio"=>2021],

            ['clave'=>281,'clave_concepto'=>2800,"descripcion"=>"Sustancias y Materiales Explosivos", "anio"=>2021],
            ['clave'=>282,'clave_concepto'=>2800,"descripcion"=>"Materiales de Seguridad Pública", "anio"=>2021],
            ['clave'=>283,'clave_concepto'=>2800,"descripcion"=>"Prendas de Protección para Seguridad Pública y Nacional", "anio"=>2021],

            ['clave'=>291,'clave_concepto'=>2900,"descripcion"=>"Herramientas Menores", "anio"=>2021],
            ['clave'=>292,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Edificios", "anio"=>2021],
            ['clave'=>293,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Mobiliario y Equipo de Administración, Educacional y Recreativo", "anio"=>2021],
            ['clave'=>294,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Equipo de Cómputo y Tecnologías de la Información", "anio"=>2021],
            ['clave'=>295,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Equipo e Instrumental Médico y de Laboratorio", "anio"=>2021],
            ['clave'=>296,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Equipo de Transporte", "anio"=>2021],
            ['clave'=>297,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Equipo de Defensa y Seguridad", "anio"=>2021],
            ['clave'=>298,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores de Maquinaria y Otros Equipos", "anio"=>2021],
            ['clave'=>299,'clave_concepto'=>2900,"descripcion"=>"Refacciones y Accesorios Menores Otros Bienes Muebles", "anio"=>2021],

            ['clave'=>311,'clave_concepto'=>3100,"descripcion"=>"Energía Eléctrica", "anio"=>2021],
            ['clave'=>312,'clave_concepto'=>3100,"descripcion"=>"Gas", "anio"=>2021],
            ['clave'=>313,'clave_concepto'=>3100,"descripcion"=>"Agua", "anio"=>2021],
            ['clave'=>314,'clave_concepto'=>3100,"descripcion"=>"Telefonía Tradicional", "anio"=>2021],
            ['clave'=>315,'clave_concepto'=>3100,"descripcion"=>"Telefonía Celular", "anio"=>2021],
            ['clave'=>316,'clave_concepto'=>3100,"descripcion"=>"Servicios de Telecomunicaciones y Satélites", "anio"=>2021],
            ['clave'=>317,'clave_concepto'=>3100,"descripcion"=>"Servicios de Acceso de Internet, Redes y Procesamiento de Información", "anio"=>2021],
            ['clave'=>318,'clave_concepto'=>3100,"descripcion"=>"Servicios Postales y Telegráficos", "anio"=>2021],
            ['clave'=>319,'clave_concepto'=>3100,"descripcion"=>"Servicios Integrales y Otros Servicios", "anio"=>2021],

            ['clave'=>321,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Terrenos", "anio"=>2021],
            ['clave'=>322,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Edificios", "anio"=>2021],
            ['clave'=>323,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Mobiliario y Equipo de Administración, Educacional y Recreativo", "anio"=>2021],
            ['clave'=>324,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Equipo e Instrumental Médico y de Laboratorio", "anio"=>2021],
            ['clave'=>325,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Equipo de Transporte", "anio"=>2021],
            ['clave'=>326,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Maquinaria, Otros Equipos y Herramientas", "anio"=>2021],
            ['clave'=>327,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento de Activos Intangibles", "anio"=>2021],
            ['clave'=>328,'clave_concepto'=>3200,"descripcion"=>"Arrendamiento Financiero", "anio"=>2021],
            ['clave'=>329,'clave_concepto'=>3200,"descripcion"=>"Otros Arrendamientos", "anio"=>2021],

            ['clave'=>331,'clave_concepto'=>3300,"descripcion"=>"Servicios Legales, de Contabilidad, Auditoría y Relacionados", "anio"=>2021],
            ['clave'=>332,'clave_concepto'=>3300,"descripcion"=>"Servicios de Diseño, Arquitectura, Ingeniería y Actividades Relacionadas", "anio"=>2021],
            ['clave'=>333,'clave_concepto'=>3300,"descripcion"=>"Servicios de Consultoría Administrativa, Procesos, Técnica y en Tecnologías de la Información", "anio"=>2021],
            ['clave'=>334,'clave_concepto'=>3300,"descripcion"=>"Servicios de Capacitación", "anio"=>2021],
            ['clave'=>335,'clave_concepto'=>3300,"descripcion"=>"Servicios de Investigación Científica y Desarrollo", "anio"=>2021],
            ['clave'=>336,'clave_concepto'=>3300,"descripcion"=>"Servicios de Apoyo Administrativo, Traducción, Fotocopiado e Impresión", "anio"=>2021],
            ['clave'=>337,'clave_concepto'=>3300,"descripcion"=>"Servicios de Protección y Seguridad", "anio"=>2021],
            ['clave'=>338,'clave_concepto'=>3300,"descripcion"=>"Servicios de Vigilancia", "anio"=>2021],
            ['clave'=>339,'clave_concepto'=>3300,"descripcion"=>"Servicios Profesionales, Científicos y Técnicos Integrales", "anio"=>2021],

            ['clave'=>341,'clave_concepto'=>3400,"descripcion"=>"Servicios Financieros y Bancarios", "anio"=>2021],
            ['clave'=>342,'clave_concepto'=>3400,"descripcion"=>"Servicios de Cobranza, Investigación Crediticia y Similar", "anio"=>2021],
            ['clave'=>343,'clave_concepto'=>3400,"descripcion"=>"Servicios de Recaudación, Traslado y Custodia de Valores", "anio"=>2021],
            ['clave'=>344,'clave_concepto'=>3400,"descripcion"=>"Seguros de Responsabilidad Patrimonial y Fianzas", "anio"=>2021],
            ['clave'=>345,'clave_concepto'=>3400,"descripcion"=>"Seguro de Bienes Patrimoniales", "anio"=>2021],
            ['clave'=>346,'clave_concepto'=>3400,"descripcion"=>"Almacenaje, Envase y Embalaje", "anio"=>2021],
            ['clave'=>347,'clave_concepto'=>3400,"descripcion"=>"Fletes y Maniobras", "anio"=>2021],
            ['clave'=>348,'clave_concepto'=>3400,"descripcion"=>"Comisiones por Ventas", "anio"=>2021],
            ['clave'=>349,'clave_concepto'=>3400,"descripcion"=>"Servicios Financieros, Bancarios y Comerciales Integrales", "anio"=>2021],

            ['clave'=>351,'clave_concepto'=>3500,"descripcion"=>"Conservación y Mantenimiento Menor de Inmuebles", "anio"=>2021],
            ['clave'=>352,'clave_concepto'=>3500,"descripcion"=>"Instalación, Reparación y Mantenimiento de Mobiliario y Equipo de Administración, Educacional y Recreativo", "anio"=>2021],
            ['clave'=>353,'clave_concepto'=>3500,"descripcion"=>"Instalación, Reparación y Mantenimiento de Equipo de Cómputo y Tecnologías de la Información", "anio"=>2021],
            ['clave'=>354,'clave_concepto'=>3500,"descripcion"=>"Instalación, Reparación y Mantenimiento de Equipo e Instrumental Médico y de Laboratorio", "anio"=>2021],
            ['clave'=>355,'clave_concepto'=>3500,"descripcion"=>"Reparación y Mantenimiento de Equipo de Transporte", "anio"=>2021],
            ['clave'=>356,'clave_concepto'=>3500,"descripcion"=>"Reparación y Mantenimiento de Equipo de Defensa y Seguridad", "anio"=>2021],
            ['clave'=>357,'clave_concepto'=>3500,"descripcion"=>"Instalación, Reparación y Mantenimiento de Maquinaria, Otros Equipos y Herramienta", "anio"=>2021],
            ['clave'=>358,'clave_concepto'=>3500,"descripcion"=>"Servicios de Limpieza y Manejo de Desechos", "anio"=>2021],
            ['clave'=>359,'clave_concepto'=>3500,"descripcion"=>"Servicios de Jardinería y Fumigación", "anio"=>2021],

            ['clave'=>361,'clave_concepto'=>3600,"descripcion"=>"Difusión por Radio, Televisión y Otros Medios de Mensajes Sobre Programas y Actividades Gubernamentales", "anio"=>2021],
            ['clave'=>362,'clave_concepto'=>3600,"descripcion"=>"Difusión por Radio, Televisión y Otros Medios de Mensajes Comerciales para Promover la Venta de Bienes o Servicios", "anio"=>2021],
            ['clave'=>363,'clave_concepto'=>3600,"descripcion"=>"Servicios de Creatividad, Preproducción y Producción de Publicidad, Excepto Internet", "anio"=>2021],
            ['clave'=>364,'clave_concepto'=>3600,"descripcion"=>"Servicios de Revelado de Fotografías", "anio"=>2021],
            ['clave'=>365,'clave_concepto'=>3600,"descripcion"=>"Servicios de la Industria Fílmica, del Sonido y del Video", "anio"=>2021],
            ['clave'=>366,'clave_concepto'=>3600,"descripcion"=>"Servicio de Creación y Difusión de Contenido Exclusivamente a Través de Internet", "anio"=>2021],
            ['clave'=>369,'clave_concepto'=>3600,"descripcion"=>"Otros Servicios de Información", "anio"=>2021],

            ['clave'=>371,'clave_concepto'=>3700,"descripcion"=>"Pasajes Aéreos", "anio"=>2021],
            ['clave'=>372,'clave_concepto'=>3700,"descripcion"=>"Pasajes Terrestres", "anio"=>2021],
            ['clave'=>373,'clave_concepto'=>3700,"descripcion"=>"Pasajes Marítimos, Lacustres y Fluviales", "anio"=>2021],
            ['clave'=>374,'clave_concepto'=>3700,"descripcion"=>"Autotransporte", "anio"=>2021],
            ['clave'=>375,'clave_concepto'=>3700,"descripcion"=>"Viáticos en el País", "anio"=>2021],
            ['clave'=>376,'clave_concepto'=>3700,"descripcion"=>"Viáticos en el Extranjero", "anio"=>2021],
            ['clave'=>377,'clave_concepto'=>3700,"descripcion"=>"Gastos de Instalación y Traslado de Menaje", "anio"=>2021],
            ['clave'=>378,'clave_concepto'=>3700,"descripcion"=>"Servicios Integrales de Traslado y Viáticos", "anio"=>2021],
            ['clave'=>379,'clave_concepto'=>3700,"descripcion"=>"Otros Servicios de Traslado y Hospedaje", "anio"=>2021],

            ['clave'=>381,'clave_concepto'=>3800,"descripcion"=>"Gastos de Ceremonial", "anio"=>2021],
            ['clave'=>382,'clave_concepto'=>3800,"descripcion"=>"Gastos de Orden Social y Cultural", "anio"=>2021],
            ['clave'=>383,'clave_concepto'=>3800,"descripcion"=>"Congresos y Convenciones", "anio"=>2021],
            ['clave'=>384,'clave_concepto'=>3800,"descripcion"=>"Exposiciones", "anio"=>2021],
            ['clave'=>385,'clave_concepto'=>3800,"descripcion"=>"Gastos de Representación", "anio"=>2021],

            ['clave'=>391,'clave_concepto'=>3900,"descripcion"=>"Servicios Funerarios y de Cementerios", "anio"=>2021],
            ['clave'=>392,'clave_concepto'=>3900,"descripcion"=>"Impuestos y Derechos", "anio"=>2021],
            ['clave'=>393,'clave_concepto'=>3900,"descripcion"=>"Impuestos y Derechos de Importación", "anio"=>2021],
            ['clave'=>394,'clave_concepto'=>3900,"descripcion"=>"Sentencias y Resoluciones por Autoridad Competente", "anio"=>2021],
            ['clave'=>395,'clave_concepto'=>3900,"descripcion"=>"Penas, Multas, Accesorios y Actualizaciones", "anio"=>2021],
            ['clave'=>396,'clave_concepto'=>3900,"descripcion"=>"Otros Gastos por Responsabilidades", "anio"=>2021],
            ['clave'=>397,'clave_concepto'=>3900,"descripcion"=>"Utilidades", "anio"=>2021],
            ['clave'=>398,'clave_concepto'=>3900,"descripcion"=>"Impuesto Sobre Nóminas y Otros que se Deriven de una Relación Laboral", "anio"=>2021],
            ['clave'=>399,'clave_concepto'=>3900,"descripcion"=>"Otros Servicios Generales", "anio"=>2021],

            ['clave'=>411,'clave_concepto'=>4100,"descripcion"=>"Asignaciones Presupuestarias al Poder Ejecutivo", "anio"=>2021],
            ['clave'=>412,'clave_concepto'=>4100,"descripcion"=>"Asignaciones Presupuestarias al Poder Legislativo", "anio"=>2021],
            ['clave'=>413,'clave_concepto'=>4100,"descripcion"=>"Asignaciones Presupuestarias al Poder Judicial", "anio"=>2021],
            ['clave'=>414,'clave_concepto'=>4100,"descripcion"=>"Asignaciones Presupuestarias a Órganos Autónomos", "anio"=>2021],
            ['clave'=>415,'clave_concepto'=>4100,"descripcion"=>"Transferencias Internas Otorgadas a Entidades Paraestatales no Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>416,'clave_concepto'=>4100,"descripcion"=>"Transferencias Internas Otorgadas a Entidades Paraestatales Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>417,'clave_concepto'=>4100,"descripcion"=>"Transferencias Internas Otorgadas a Fideicomisos Públicos Empresariales y no Financieros", "anio"=>2021],
            ['clave'=>418,'clave_concepto'=>4100,"descripcion"=>"Transferencias Internas Otorgadas a Instituciones Paraestatales Públicas Financieras", "anio"=>2021],
            ['clave'=>419,'clave_concepto'=>4100,"descripcion"=>"Transferencias Internas Otorgadas a Fideicomisos Financieros", "anio"=>2021],

            ['clave'=>421,'clave_concepto'=>4200,"descripcion"=>"Transferencias Otorgadas a Entidades Paraestatales no Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>422,'clave_concepto'=>4200,"descripcion"=>"Transferencias Otorgadas para Entidades Paraestatales Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>423,'clave_concepto'=>4200,"descripcion"=>"Transferencias Otorgadas para Instituciones Paraestatales Públicas Financieras", "anio"=>2021],
            ['clave'=>424,'clave_concepto'=>4200,"descripcion"=>"Transferencias Otorgadas a Entidades Federativas y Municipios", "anio"=>2021],
            ['clave'=>425,'clave_concepto'=>4200,"descripcion"=>"Transferencias a Fideicomisos de Entidades Federativas y Municipios", "anio"=>2021],

            ['clave'=>431,'clave_concepto'=>4300,"descripcion"=>"Subsidios a la Producción", "anio"=>2021],
            ['clave'=>432,'clave_concepto'=>4300,"descripcion"=>"Subsidios a la Distribución", "anio"=>2021],
            ['clave'=>433,'clave_concepto'=>4300,"descripcion"=>"Subsidios a la Inversión", "anio"=>2021],
            ['clave'=>434,'clave_concepto'=>4300,"descripcion"=>"Subsidios a la Prestación de Servicios Públicos", "anio"=>2021],
            ['clave'=>435,'clave_concepto'=>4300,"descripcion"=>"Subsidios para Cubrir Diferenciales de Tasas de Interés", "anio"=>2021],
            ['clave'=>436,'clave_concepto'=>4300,"descripcion"=>"Subsidios a la Vivienda", "anio"=>2021],
            ['clave'=>437,'clave_concepto'=>4300,"descripcion"=>"Subvenciones al Consumo", "anio"=>2021],
            ['clave'=>438,'clave_concepto'=>4300,"descripcion"=>"Subsidios a Entidades Federativas y Municipios", "anio"=>2021],
            ['clave'=>439,'clave_concepto'=>4300,"descripcion"=>"Otros Subsidios", "anio"=>2021],

            ['clave'=>441,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Personas", "anio"=>2021],
            ['clave'=>442,'clave_concepto'=>4400,"descripcion"=>"Becas y Otras Ayudas para Programas de Capacitación", "anio"=>2021],
            ['clave'=>443,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Instituciones de Enseñanza", "anio"=>2021],
            ['clave'=>444,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Actividades Científicas o Académicas", "anio"=>2021],
            ['clave'=>445,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Instituciones Sin Fines de Lucro", "anio"=>2021],
            ['clave'=>446,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Cooperativas", "anio"=>2021],
            ['clave'=>447,'clave_concepto'=>4400,"descripcion"=>"Ayudas Sociales a Entidades de Interés Público", "anio"=>2021],
            ['clave'=>448,'clave_concepto'=>4400,"descripcion"=>"Ayudas por Desastres Naturales y Otros Siniestros", "anio"=>2021],

            ['clave'=>451,'clave_concepto'=>4500,"descripcion"=>"Pensiones", "anio"=>2021],
            ['clave'=>452,'clave_concepto'=>4500,"descripcion"=>"Jubilaciones", "anio"=>2021],
            ['clave'=>459,'clave_concepto'=>4500,"descripcion"=>"Otras Pensiones y Jubilaciones", "anio"=>2021],

            ['clave'=>461,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos del Poder Ejecutivo", "anio"=>2021],
            ['clave'=>462,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos del Poder Legislativo", "anio"=>2021],
            ['clave'=>463,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos del Poder Judicial", "anio"=>2021],
            ['clave'=>464,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos Públicos de Entidades Paraestatales no Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>465,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos Públicos de Entidades Paraestatales Empresariales y no Financieras", "anio"=>2021],
            ['clave'=>466,'clave_concepto'=>4600,"descripcion"=>"Transferencias a Fideicomisos de Instituciones Públicas Financieras", "anio"=>2021],
            ['clave'=>469,'clave_concepto'=>4600,"descripcion"=>"Otras Transferencias a Fideicomisos", "anio"=>2021],

            ['clave'=>471,'clave_concepto'=>4700,"descripcion"=>"Transferencias por Obligación de Ley", "anio"=>2021],

            ['clave'=>481,'clave_concepto'=>4800,"descripcion"=>"Donativos a Instituciones sin Fines de Lucro", "anio"=>2021],
            ['clave'=>482,'clave_concepto'=>4800,"descripcion"=>"Donativos a Entidades Federativas", "anio"=>2021],
            ['clave'=>483,'clave_concepto'=>4800,"descripcion"=>"Donativos a Fideicomisos Privados", "anio"=>2021],
            ['clave'=>484,'clave_concepto'=>4800,"descripcion"=>"Donativos a Fideicomisos Estatales", "anio"=>2021],
            ['clave'=>485,'clave_concepto'=>4800,"descripcion"=>"Donativos Internacionales", "anio"=>2021],

            ['clave'=>491,'clave_concepto'=>4900,"descripcion"=>"Transferencias para Gobiernos Extranjeros", "anio"=>2021],
            ['clave'=>492,'clave_concepto'=>4900,"descripcion"=>"Transferencias para Organismos Internacionales", "anio"=>2021],
            ['clave'=>493,'clave_concepto'=>4900,"descripcion"=>"Transferencia para el Sector Privado Externo", "anio"=>2021],

            ['clave'=>511,'clave_concepto'=>5100,"descripcion"=>"Muebles de Oficina y Estantería", "anio"=>2021],
            ['clave'=>512,'clave_concepto'=>5100,"descripcion"=>"Muebles, Excepto de Oficina y Estantería", "anio"=>2021],
            ['clave'=>513,'clave_concepto'=>5100,"descripcion"=>"Bienes Artísticos, Culturales y Científicos", "anio"=>2021],
            ['clave'=>514,'clave_concepto'=>5100,"descripcion"=>"Objetos de Valor", "anio"=>2021],
            ['clave'=>515,'clave_concepto'=>5100,"descripcion"=>"Equipo de Cómputo y de Tecnologías de la Información", "anio"=>2021],
            ['clave'=>519,'clave_concepto'=>5100,"descripcion"=>"Otros Mobiliarios y Equipos de Administración", "anio"=>2021],

            ['clave'=>521,'clave_concepto'=>5200,"descripcion"=>"Equipos y Aparatos Audiovisuales", "anio"=>2021],
            ['clave'=>522,'clave_concepto'=>5200,"descripcion"=>"Aparatos Deportivos", "anio"=>2021],
            ['clave'=>523,'clave_concepto'=>5200,"descripcion"=>"Cámaras Fotográficas y de Video", "anio"=>2021],
            ['clave'=>529,'clave_concepto'=>5200,"descripcion"=>"Otro Mobiliario y Equipo Educacional y Recreativo", "anio"=>2021],

            ['clave'=>531,'clave_concepto'=>5300,"descripcion"=>"Equipo Médico y de Laboratorio", "anio"=>2021],
            ['clave'=>532,'clave_concepto'=>5300,"descripcion"=>"Instrumental Médico y de Laboratorio", "anio"=>2021],

            ['clave'=>541,'clave_concepto'=>5400,"descripcion"=>"Vehículos y Equipo Terrestre", "anio"=>2021],
            ['clave'=>542,'clave_concepto'=>5400,"descripcion"=>"Carrocerías y Remolques", "anio"=>2021],
            ['clave'=>543,'clave_concepto'=>5400,"descripcion"=>"Equipo Aeroespacial", "anio"=>2021],
            ['clave'=>544,'clave_concepto'=>5400,"descripcion"=>"Equipo ferroviario", "anio"=>2021],
            ['clave'=>545,'clave_concepto'=>5400,"descripcion"=>"Embarcaciones", "anio"=>2021],
            ['clave'=>549,'clave_concepto'=>5400,"descripcion"=>"Otros Equipos de Transporte", "anio"=>2021],

            ['clave'=>551,'clave_concepto'=>5500,"descripcion"=>"Equipo de Defensa y Seguridad", "anio"=>2021],

            ['clave'=>561,'clave_concepto'=>5600,"descripcion"=>"Maquinaria y Equipo Agropecuario", "anio"=>2021],
            ['clave'=>562,'clave_concepto'=>5600,"descripcion"=>"Maquinaria y Equipo Industrial", "anio"=>2021],
            ['clave'=>563,'clave_concepto'=>5600,"descripcion"=>"Maquinaria y Equipo de Construcción", "anio"=>2021],
            ['clave'=>564,'clave_concepto'=>5600,"descripcion"=>"Sistemas de Aire Acondicionado, Calefacción y de Refrigeración Industrial y Comercial", "anio"=>2021],
            ['clave'=>565,'clave_concepto'=>5600,"descripcion"=>"Equipo de Comunicación y Telecomunicación", "anio"=>2021],
            ['clave'=>566,'clave_concepto'=>5600,"descripcion"=>"Equipos de Generación Eléctrica, Aparatos y Accesorios Eléctricos", "anio"=>2021],
            ['clave'=>567,'clave_concepto'=>5600,"descripcion"=>"Herramientas y Máquinas-Herramienta", "anio"=>2021],
            ['clave'=>569,'clave_concepto'=>5600,"descripcion"=>"Otros Equipos", "anio"=>2021],

            ['clave'=>571,'clave_concepto'=>5700,"descripcion"=>"Bovinos", "anio"=>2021],
            ['clave'=>572,'clave_concepto'=>5700,"descripcion"=>"Porcinos", "anio"=>2021],
            ['clave'=>573,'clave_concepto'=>5700,"descripcion"=>"Aves", "anio"=>2021],
            ['clave'=>574,'clave_concepto'=>5700,"descripcion"=>"Ovinos y Caprinos", "anio"=>2021],
            ['clave'=>575,'clave_concepto'=>5700,"descripcion"=>"Peces y Acuicultura", "anio"=>2021],
            ['clave'=>576,'clave_concepto'=>5700,"descripcion"=>"Equinos", "anio"=>2021],
            ['clave'=>577,'clave_concepto'=>5700,"descripcion"=>"Especies Menores y de Zoológico", "anio"=>2021],
            ['clave'=>578,'clave_concepto'=>5700,"descripcion"=>"Árboles y Plantas", "anio"=>2021],
            ['clave'=>579,'clave_concepto'=>5700,"descripcion"=>"Otros Activos Biológicos", "anio"=>2021],

            ['clave'=>581,'clave_concepto'=>5800,"descripcion"=>"Terrenos", "anio"=>2021],
            ['clave'=>582,'clave_concepto'=>5800,"descripcion"=>"Viviendas", "anio"=>2021],
            ['clave'=>583,'clave_concepto'=>5800,"descripcion"=>"Edificios no Residenciales", "anio"=>2021],
            ['clave'=>589,'clave_concepto'=>5800,"descripcion"=>"Otros Bienes Inmuebles", "anio"=>2021],

            ['clave'=>591,'clave_concepto'=>5900,"descripcion"=>"Software", "anio"=>2021],
            ['clave'=>592,'clave_concepto'=>5900,"descripcion"=>"Patentes", "anio"=>2021],
            ['clave'=>593,'clave_concepto'=>5900,"descripcion"=>"Marcas", "anio"=>2021],
            ['clave'=>594,'clave_concepto'=>5900,"descripcion"=>"Derechos", "anio"=>2021],
            ['clave'=>595,'clave_concepto'=>5900,"descripcion"=>"Concesiones", "anio"=>2021],
            ['clave'=>596,'clave_concepto'=>5900,"descripcion"=>"Franquicias", "anio"=>2021],
            ['clave'=>597,'clave_concepto'=>5900,"descripcion"=>"Licencias Informáticas e Intelectuales", "anio"=>2021],
            ['clave'=>598,'clave_concepto'=>5900,"descripcion"=>"Licencias Industriales, Comerciales y Otras", "anio"=>2021],
            ['clave'=>599,'clave_concepto'=>5900,"descripcion"=>"Otros Activos Intangibles", "anio"=>2021],

            ['clave'=>611,'clave_concepto'=>6100,"descripcion"=>"Edificación Habitacional", "anio"=>2021],
            ['clave'=>612,'clave_concepto'=>6100,"descripcion"=>"Edificación no Habitacional", "anio"=>2021],
            ['clave'=>613,'clave_concepto'=>6100,"descripcion"=>"Construcción de Obras para el Abastecimiento de Agua, Petróleo, Gas, Electricidad y Telecomunicaciones", "anio"=>2021],
            ['clave'=>614,'clave_concepto'=>6100,"descripcion"=>"División de Terrenos y Construcción de Obras de Urbanización", "anio"=>2021],
            ['clave'=>615,'clave_concepto'=>6100,"descripcion"=>"Construcción de Vías de Comunicación", "anio"=>2021],
            ['clave'=>616,'clave_concepto'=>6100,"descripcion"=>"Otras Construcciones de Ingeniería Civil u Obra Pesada", "anio"=>2021],
            ['clave'=>617,'clave_concepto'=>6100,"descripcion"=>"Instalaciones y Equipamiento en Construcciones", "anio"=>2021],
            ['clave'=>619,'clave_concepto'=>6100,"descripcion"=>"Trabajos de Acabados en Edificaciones y Otros Trabajos Especializados", "anio"=>2021],

            ['clave'=>621,'clave_concepto'=>6200,"descripcion"=>"Edificación Habitacional", "anio"=>2021],
            ['clave'=>622,'clave_concepto'=>6200,"descripcion"=>"Edificación no Habitacional", "anio"=>2021],
            ['clave'=>623,'clave_concepto'=>6200,"descripcion"=>"Construcción de Obras para el Abastecimiento de Agua, Petróleo, Gas, Electricidad y Telecomunicaciones", "anio"=>2021],
            ['clave'=>624,'clave_concepto'=>6200,"descripcion"=>"División de Terrenos y Construcción de Obras de Urbanización", "anio"=>2021],
            ['clave'=>625,'clave_concepto'=>6200,"descripcion"=>"Construcción de Vías de Comunicación", "anio"=>2021],
            ['clave'=>626,'clave_concepto'=>6200,"descripcion"=>"Otras Construcciones de Ingeniería Civil u Obra Pesada", "anio"=>2021],
            ['clave'=>627,'clave_concepto'=>6200,"descripcion"=>"Instalaciones y Equipamiento en Construcciones", "anio"=>2021],
            ['clave'=>629,'clave_concepto'=>6200,"descripcion"=>"Trabajos de Acabados en Edificaciones y Otros Trabajos Especializados", "anio"=>2021],

            ['clave'=>631,'clave_concepto'=>6300,"descripcion"=>"Estudios, Formulación y Evaluación de Proyectos Productivos no Incluidos en Conceptos Anteriores de este Capítulo", "anio"=>2021],
            ['clave'=>632,'clave_concepto'=>6300,"descripcion"=>"Ejecución de Proyectos Productivos no Incluidos en Conceptos Anteriores de este Capítulo", "anio"=>2021],

            ['clave'=>711,'clave_concepto'=>7100,"descripcion"=>"Créditos Otorgados por Entidades Federativas y Municipios al Sector Social y Privado para el Fomento de Actividades Productivas", "anio"=>2021],
            ['clave'=>712,'clave_concepto'=>7100,"descripcion"=>"Créditos Otorgados por Entidades Federativas a Municipios para el Fomento de Actividades Productivas", "anio"=>2021],

            ['clave'=>721,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en Entidades Paraestatales no Empresariales y no Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>722,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en Entidades Paraestatales Empresariales y no Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>723,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en Instituciones Paraestatales Públicas Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>724,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en el Sector Privado con Fines de Política Económica", "anio"=>2021],
            ['clave'=>725,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en Organismos Internacionales con Fines de Política Económica", "anio"=>2021],
            ['clave'=>726,'clave_concepto'=>7200,"descripcion"=>"Acciones y participaciones de capital en el sector externo con fines de política económica", "anio"=>2021],
            ['clave'=>727,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en el Sector Público con Fines de Gestión de la Liquidez.", "anio"=>2021],
            ['clave'=>728,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en el Sector Privado con Fines de Gestión de la Liquidez", "anio"=>2021],
            ['clave'=>729,'clave_concepto'=>7200,"descripcion"=>"Acciones y Participaciones de Capital en el Sector Externo con Fines de Gestión de la Liquidez", "anio"=>2021],

            ['clave'=>731,'clave_concepto'=>7300,"descripcion"=>"Bonos", "anio"=>2021],
            ['clave'=>732,'clave_concepto'=>7300,"descripcion"=>"Valores Representativos de Deuda Adquiridos con Fines de Política Económica", "anio"=>2021],
            ['clave'=>733,'clave_concepto'=>7300,"descripcion"=>"Valores Representativos de Deuda Adquiridos con Fines de Gestión de Liquidez", "anio"=>2021],
            ['clave'=>734,'clave_concepto'=>7300,"descripcion"=>"Obligaciones Negociables Adquiridas con Fines de Política Económica", "anio"=>2021],
            ['clave'=>735,'clave_concepto'=>7300,"descripcion"=>"Obligaciones Negociables Adquiridas con Fines de Gestión de Liquidez", "anio"=>2021],
            ['clave'=>739,'clave_concepto'=>7300,"descripcion"=>"Otros Valores", "anio"=>2021],

            ['clave'=>741,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos a Entidades Paraestatales no Empresariales y no Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>742,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos a Entidades Paraestatales Empresariales y no Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>743,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos a Instituciones Paraestatales Públicas Financieras con Fines de Política Económica", "anio"=>2021],
            ['clave'=>744,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos a Entidades Federativas y Municipios con Fines de Política Económica", "anio"=>2021],
            ['clave'=>745,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos al Sector Privado con Fines de Política Económica", "anio"=>2021],
            ['clave'=>746,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos al Sector Externo con Fines de Política Económica", "anio"=>2021],
            ['clave'=>747,'clave_concepto'=>7400,"descripcion"=>"Concesión de préstamos al sector público con fines de gestión de liquidez", "anio"=>2021],
            ['clave'=>748,'clave_concepto'=>7400,"descripcion"=>"Concesión de Préstamos al Sector Privado con Fines de Gestión de Liquidez", "anio"=>2021],
            ['clave'=>749,'clave_concepto'=>7400,"descripcion"=>"Concesión de préstamos al sector externo con fines de gestión de liquidez", "anio"=>2021],

            ['clave'=>751,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos del Poder Ejecutivo", "anio"=>2021],
            ['clave'=>752,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos del Poder Legislativo", "anio"=>2021],
            ['clave'=>753,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos del Poder Judicial", "anio"=>2021],
            ['clave'=>754,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos Públicos no Empresariales y no Financieros", "anio"=>2021],
            ['clave'=>755,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos Públicos Empresariales y no Financieros", "anio"=>2021],
            ['clave'=>756,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos Públicos Financieros", "anio"=>2021],
            ['clave'=>757,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos de Entidades Federativas", "anio"=>2021],
            ['clave'=>758,'clave_concepto'=>7500,"descripcion"=>"Inversiones en Fideicomisos de Municipios", "anio"=>2021],
            ['clave'=>759,'clave_concepto'=>7500,"descripcion"=>"Otras Inversiones en Fideicomisos", "anio"=>2021],

            ['clave'=>761,'clave_concepto'=>7600,"descripcion"=>"Depósitos a Largo Plazo en Moneda Nacional", "anio"=>2021],
            ['clave'=>762,'clave_concepto'=>7600,"descripcion"=>"Depósitos a Largo Plazo en Moneda Extranjera", "anio"=>2021],

            ['clave'=>791,'clave_concepto'=>7900,"descripcion"=>"Contingencias por Fenómenos Naturales", "anio"=>2021],
            ['clave'=>792,'clave_concepto'=>7900,"descripcion"=>"Contingencias Socioeconómicas", "anio"=>2021],
            ['clave'=>799,'clave_concepto'=>7900,"descripcion"=>"Otras Erogaciones Especiales", "anio"=>2021],

            ['clave'=>811,'clave_concepto'=>8100,"descripcion"=>"Fondo General de Participaciones", "anio"=>2021],
            ['clave'=>812,'clave_concepto'=>8100,"descripcion"=>"Fondo de Fomento Municipal", "anio"=>2021],
            ['clave'=>813,'clave_concepto'=>8100,"descripcion"=>"Participaciones de las Entidades Federativas a los Municipios", "anio"=>2021],
            ['clave'=>814,'clave_concepto'=>8100,"descripcion"=>"Otros Conceptos Participables de la Federación a Entidades Federativas", "anio"=>2021],
            ['clave'=>815,'clave_concepto'=>8100,"descripcion"=>"Otros Conceptos Participables de la Federación a Municipios", "anio"=>2021],
            ['clave'=>816,'clave_concepto'=>8100,"descripcion"=>"Convenios de Colaboración Administrativa", "anio"=>2021],

            ['clave'=>831,'clave_concepto'=>8300,"descripcion"=>"Aportaciones de la Federación a las Entidades Federativas", "anio"=>2021],
            ['clave'=>832,'clave_concepto'=>8300,"descripcion"=>"Aportaciones de la Federación a Municipios", "anio"=>2021],
            ['clave'=>833,'clave_concepto'=>8300,"descripcion"=>"Aportaciones de las Entidades Federativas a los Municipios", "anio"=>2021],
            ['clave'=>834,'clave_concepto'=>8300,"descripcion"=>"Aportaciones Previstas en Leyes y Decretos al Sistema de Protección Social", "anio"=>2021],
            ['clave'=>835,'clave_concepto'=>8300,"descripcion"=>"Aportaciones Previstas en Leyes y Decretos Compensatorias a Entidades Federativas y Municipios", "anio"=>2021],

            ['clave'=>851,'clave_concepto'=>8500,"descripcion"=>"Convenios de Reasignación", "anio"=>2021],
            ['clave'=>852,'clave_concepto'=>8500,"descripcion"=>"Convenios de Descentralización", "anio"=>2021],
            ['clave'=>853,'clave_concepto'=>8500,"descripcion"=>"Otros Convenios", "anio"=>2021],

            ['clave'=>911,'clave_concepto'=>9100,"descripcion"=>"Amortización de la Deuda Interna con Instituciones de Crédito", "anio"=>2021],
            ['clave'=>912,'clave_concepto'=>9100,"descripcion"=>"Amortización de la Deuda Interna por Emisión de Títulos y Valores", "anio"=>2021],
            ['clave'=>913,'clave_concepto'=>9100,"descripcion"=>"Amortización de Arrendamientos Financieros Nacionales", "anio"=>2021],
            ['clave'=>914,'clave_concepto'=>9100,"descripcion"=>"Amortización de la Deuda Externa con Instituciones de Crédito", "anio"=>2021],
            ['clave'=>915,'clave_concepto'=>9100,"descripcion"=>"Amortización de Deuda Externa con Organismos Financieros Internacionales", "anio"=>2021],
            ['clave'=>916,'clave_concepto'=>9100,"descripcion"=>"Amortización de la Deuda Bilateral", "anio"=>2021],
            ['clave'=>917,'clave_concepto'=>9100,"descripcion"=>"Amortización de la Deuda Externa por Emisión de Títulos y Valores", "anio"=>2021],
            ['clave'=>918,'clave_concepto'=>9100,"descripcion"=>"Amortización de Arrendamientos Financieros Internacionales", "anio"=>2021],

            ['clave'=>921,'clave_concepto'=>9200,"descripcion"=>"Intereses de la Deuda Interna con Instituciones de Crédito", "anio"=>2021],
            ['clave'=>922,'clave_concepto'=>9200,"descripcion"=>"Intereses Derivados de la Colocación de Títulos y Valores", "anio"=>2021],
            ['clave'=>923,'clave_concepto'=>9200,"descripcion"=>"Intereses por Arrendamientos Financieros Nacionales", "anio"=>2021],
            ['clave'=>924,'clave_concepto'=>9200,"descripcion"=>"Intereses de la Deuda Externa con Instituciones de Crédito", "anio"=>2021],
            ['clave'=>925,'clave_concepto'=>9200,"descripcion"=>"Intereses de la Deuda con Organismos Financieros Internacionales", "anio"=>2021],
            ['clave'=>926,'clave_concepto'=>9200,"descripcion"=>"Intereses de la Deuda Bilateral", "anio"=>2021],
            ['clave'=>927,'clave_concepto'=>9200,"descripcion"=>"Intereses Derivados de la Colocación de Títulos y Valores en el Exterior", "anio"=>2021],
            ['clave'=>928,'clave_concepto'=>9200,"descripcion"=>"Intereses por Arrendamientos Financieros Internacionales", "anio"=>2021],

            ['clave'=>931,'clave_concepto'=>9300,"descripcion"=>"Comisiones de la Deuda Pública Interna", "anio"=>2021],
            ['clave'=>932,'clave_concepto'=>9300,"descripcion"=>"Comisiones de la Deuda Pública Externa", "anio"=>2021],

            ['clave'=>941,'clave_concepto'=>9400,"descripcion"=>"Gastos de la Deuda Pública Interna", "anio"=>2021],
            ['clave'=>942,'clave_concepto'=>9400,"descripcion"=>"Gastos de la Deuda Pública Externa", "anio"=>2021],

            ['clave'=>951,'clave_concepto'=>9500,"descripcion"=>"Costos por Coberturas", "anio"=>2021],

            ['clave'=>961,'clave_concepto'=>9600,"descripcion"=>"Apoyos a Intermediarios Financieros", "anio"=>2021],
            ['clave'=>962,'clave_concepto'=>9600,"descripcion"=>"Apoyos a Ahorradores y Deudores del Sistema Financiero Nacional", "anio"=>2021],

            ['clave'=>991,'clave_concepto'=>9900,"descripcion"=>"ADEFAS", "anio"=>2021],

        ];

        foreach ($list as $item) {
            \App\Models\PartidaGenerica::create($item);
        }
    }
}
